# model = input("자동차 모델 입력 구다사이: ")
# msg =""
# bmw =["m1","m2","m3","m4"]
# tesla = ["Y","X"]
# lexus = ["ES","LS"]
# genesis = ["G80","G90"]
# for i in bmw:
#     if i == model:
#         msg = "bmw"
#         break

# for i in tesla:
#     if i == model:
#         msg = "tesla"
#         break
# for i in lexus:
#     if i == model:
#         msg = "lexus"
#         break

# for i in genesis:
#     if i == model:
#         msg = "genesis"
#         break
    
    


model = input("자동차 모델 입력 구다사이: ")
msg =""
bmw =["m1","m2","m3","m4"]
tesla = ["Y","X"]
lexus = ["ES","LS"]
genesis = ["G80","G90"]
car =[bmw,tesla,lexus,genesis]


